package sshcmd

import (
	"fmt"
	"strings"
	"unicode"

	"sshbrowse/internal/profile"
)

const maxProxyCommandBytes = 32 * 1024

// ConnectionArgv resolves saved jump references while leaving raw ProxyJump
// syntax and the platform's normal ssh_config resolution to OpenSSH.
func ConnectionArgv(connection profile.Connection, saved []profile.Connection, sftp bool) ([]string, error) {
	if connection.JumpConnectionID != "" {
		connection.Host = jumpTargetHost(connection.Host)
	}
	hops, err := profile.JumpChain(connection, saved)
	if err != nil {
		return nil, err
	}
	proxy, err := savedJumpProxy(connection.Host, hops)
	if err != nil {
		return nil, err
	}
	var argv []string
	if sftp {
		argv = SFTPArgv(connection)
	} else {
		argv = Argv(connection)
	}
	if proxy != "" {
		argv = proxyOptions(argv, proxy)
	}
	return argv, nil
}

func savedJumpProxy(targetHost string, hops []profile.Connection) (string, error) {
	proxy := ""
	for i := len(hops) - 1; i >= 0; i-- {
		// %h is substituted before shell parsing. Permit OpenSSH aliases (including
		// punctuation and Unicode), but reject shell delimiters in app-supplied hosts.
		// HostName values resolved by ssh_config remain OpenSSH's responsibility.
		host := targetHost
		if i > 0 {
			host = jumpTargetHost(hops[i-1].Host)
		}
		if strings.IndexFunc(host, func(r rune) bool {
			return unicode.IsControl(r) || unicode.IsSpace(r) || strings.ContainsRune("'\"`$;\\|&<>", r)
		}) >= 0 {
			return "", fmt.Errorf("saved jump target host contains unsupported characters")
		}
		hop := hops[i]
		hop.Host = jumpTargetHost(hop.Host)
		// -W is a transport hop. Reuse transport options without the hop's session
		// tunnels, X11, or agent forwarding. Local agent access is inherited.
		argv := connectionOptions(hop, SSHPath, "-p")
		argv = append(argv, "--", destination(hop.User, hop.Host))
		if proxy != "" {
			argv = proxyOptions(argv, proxy)
		}
		// Preserve literal tokens (including nested proxies') for the hop's own
		// OpenSSH processing. Only -W's target belongs to the outer client.
		for j, arg := range argv {
			argv[j] = strings.ReplaceAll(arg, "%", "%%")
		}
		argv = insertOptions(argv, "-W", "[%h]:%p")
		proxy = quoteProxyCommand(argv)
		if len(proxy) > maxProxyCommandBytes {
			return "", fmt.Errorf("saved jump proxy exceeds %d bytes", maxProxyCommandBytes)
		}
	}
	return proxy, nil
}

// ssh -W transports bytes, not a passed socket descriptor. Match the implicit
// proxy generated by -J even when ssh_config enables ProxyUseFdpass.
func proxyOptions(argv []string, proxy string) []string {
	return insertOptions(argv, "-o", "ProxyUseFdpass=no", "-o", "ProxyCommand="+proxy)
}

// -W brackets its expanded %h to support IPv6. Keep the hostname itself bare
// so a bracketed saved literal does not become [[address]] in the transport.
func jumpTargetHost(host string) string {
	if strings.HasPrefix(host, "[") && strings.HasSuffix(host, "]") && strings.Contains(host, ":") {
		return host[1 : len(host)-1]
	}
	return host
}

// Both builders end with -- and a destination. Insert transport options before it.
func insertOptions(argv []string, options ...string) []string {
	end := len(argv) - 2
	result := append([]string{}, argv[:end]...)
	result = append(result, options...)
	return append(result, argv[end:]...)
}
